### ISSUE TITLE
Tina-v831 won't burn to sd card

### ISSUE THREAD

**Issue by Captnlink** [Tina-V833/tina-V833#1]
Hi,

So the issue here is that after building the code from the source and packing the images, I try to burn the image with either PheonixCard or Pheonix Suit but the device is never programed.

After looking at the kernel logs from the debug view in PheonixSuit, when I load the image or when I try to burn it, I get this log: "unknown Tools command".

I am building the image for the v831 and trying to burn the image through the MAIX_II Dock dev kit.

To arrive at the image, I've updated some packages inside the Linux part but this is as far I touched the code. 

Setup:
1- Download sources as the readme
2- Build sources as in the readme
3- Pack and pack -d to have uart0 and card0 images
4- try using PheonixSuit or PheonixCard to upload images through MAIX_II Dock (a v831 devkit)

Logs from Kernel
> 00000001	1:32:54 PM	[2552] Img_OpenItem now! 	
> 00000002	1:32:54 PM	[2552] Img_OpenItem[PXTOOLSB][xxxxxxxxxxxxxxxx]	
> 00000003	1:32:54 PM	[2552] Closing image now! 	
> 00000004	1:32:54 PM	[2552] CloseImage OK 	
> 00000005	1:32:54 PM	[2552] unknown Tools command 	
> 00000006	1:32:54 PM	[2552] **************************************	
> 00000007	1:32:54 PM	[2552] unknown Tools command 	
> 00000008	1:32:54 PM	[2552] *********global_info_entry***********	
> 00000009	1:32:54 PM	[2552] unknown Tools command 	
> 00000010	1:32:54 PM	[2552] **************************************	
> 00000011	1:32:54 PM	[2552] Load "privatedata.ini" Failed: .\ProProcMan.cpp @ 2107 	
> 00000012	1:32:55 PM	[2552] DeviceEvent jzr = NULL: wParam=0x7  lParam=0x0 	
> 00000013	1:33:05 PM	[2552] DeviceEvent jzr = NULL: wParam=0x7  lParam=0x0 	
> 00000014	1:33:13 PM	[2552] DevicePlugIn: \\?\USB#VID_1F3A&PID_EFE8#5&26471407&0&1#{0e57c50f-0ccc-4ad2-a895-93c5ed119860},BOOL to AWUSB:1 	
> 00000015	1:33:13 PM	[2552] unknown Tools command 	
> 00000016	1:33:13 PM	[2552] ***************************************
> ...

So, Can someone help?

**Comment by YuzukiTsuru** [comment]
For now, v831 has very limited support and can only compile and package the system but can't run. MAIX_II Dock isn't supported neither. There's a lot of patches to deal with.

The support of MAIX_II Dock is on schedule.

**Comment by Captnlink** [comment]
Thanks for the information!
